import { GameUnit } from './types'; // Removed WordItem to fix TS6133

export const UNITS: GameUnit[] = [
    {
        id: 'unit1',
        title: 'Lesson 1',
        color: 'bg-red-500',
        icon: '🇨🇳',
        words: [
            { id: 'hao', word: '好', english: 'Good', emoji: '' },
            { id: 'ni', word: '你', english: 'You', emoji: '' },
            { id: 'wo', word: '我', english: 'Me', emoji: '' },
            { id: 'jiao', word: '叫', english: 'Called', emoji: '' },
            { id: 'shenme', word: '什么', english: 'What', emoji: '' },
            { id: 'mingzi', word: '名字', english: 'Name', emoji: '' },
            { id: 'xing', word: '姓', english: 'Surname', emoji: '' },
            { id: 'gui', word: '贵', english: 'Noble', emoji: '' },
            { id: 'qing', word: '请', english: 'Please', emoji: '' },
            { id: 'wen', word: '问', english: 'Ask', emoji: '' },
            { id: 'wang', word: '王', english: 'Wang', emoji: '' },
            { id: 'li', word: '李', english: 'Li', emoji: '' },
            { id: 'xiaojie', word: '小姐', english: 'Miss', emoji: '' },
            { id: 'xiansheng', word: '先生', english: 'Mr.', emoji: '' },
            { id: 'ne', word: '呢', english: 'How about', emoji: '' },
            { id: 'pengyou', word: '朋友', english: 'Friend', emoji: '' },
            { id: 'zhongwen', word: '中文', english: 'Chinese', emoji: '' },
            { id: 'yingwen', word: '英文', english: 'English', emoji: '' },
            { id: 'bu', word: '不', english: 'No', emoji: '' },
            { id: 'shi', word: '是', english: 'Is/Am/Are', emoji: '' },
            { id: 'ta1', word: '他', english: 'He', emoji: '' },
            { id: 'ta2', word: '她', english: 'She', emoji: '' },
            { id: 'zhe', word: '这', english: 'This', emoji: '' },
            { id: 'na', word: '那', english: 'That', emoji: '' },
            { id: 'ye', word: '也', english: 'Also', emoji: '' },
            { id: 'laoshi', word: '老师', english: 'Teacher', emoji: '' },
            { id: 'xuesheng', word: '学生', english: 'Student', emoji: '' },
            { id: 'ma', word: '吗', english: '?', emoji: '' },
            { id: 'ren', word: '人', english: 'Person', emoji: '' },
            { id: 'zhongguo', word: '中国', english: 'China', emoji: '' },
            { id: 'beijing', word: '北京', english: 'Beijing', emoji: '' },
            { id: 'zhuzai', word: '住在', english: 'Live in', emoji: '' },
            { id: 'meiguo', word: '美国', english: 'USA', emoji: '' },
            { id: 'xiaweiyi', word: '夏威夷', english: 'Hawaii', emoji: '' },
            { id: 'niuyue', word: '纽约', english: 'New York', emoji: '' },
        ],
    },
    {
        id: 'unit2',
        title: 'Lesson 2',
        color: 'bg-orange-500',
        icon: '👨👩👧',
        words: [
            { id: 'women', word: '我们', english: 'We', emoji: '' },
            { id: 'nimen', word: '你们', english: 'You (pl)', emoji: '' },
            { id: 'tamen', word: '他们', english: 'They', emoji: '' },
            { id: 'dou', word: '都', english: 'Both/All', emoji: '' },
            { id: 'shuo', word: '说', english: 'Speak', emoji: '' },
            { id: 'de', word: '的', english: "'s", emoji: '' },
            { id: 'wode', word: '我的', english: 'My', emoji: '' },
            { id: 'nide', word: '你的', english: 'Your', emoji: '' },
            { id: 'tade', word: '他的/她的', english: 'His/Her', emoji: '' },
            { id: 'you', word: '有', english: 'Have', emoji: '' },
            { id: 'meiyou', word: '没有', english: "Don't have", emoji: '' },
            { id: 'he', word: '和', english: 'And', emoji: '' },
            { id: 'xiang', word: '想', english: 'Want', emoji: '' },
            { id: 'xihuan', word: '喜欢', english: 'Like', emoji: '' },
            { id: 'baba', word: '爸爸', english: 'Dad', emoji: '' },
            { id: 'mama', word: '妈妈', english: 'Mom', emoji: '' },
            { id: 'jiejie', word: '姐姐', english: 'Big Sister', emoji: '' },
            { id: 'gege', word: '哥哥', english: 'Big Brother', emoji: '' },
            { id: 'didi', word: '弟弟', english: 'Little Brother', emoji: '' },
            { id: 'meimei', word: '妹妹', english: 'Little Sister', emoji: '' },
            { id: 'dage', word: '大哥', english: 'Eldest Brother', emoji: '' },
            { id: 'erzi', word: '儿子', english: 'Son', emoji: '' },
            { id: 'zhaopian', word: '照片', english: 'Photo', emoji: '' },
            { id: 'ge', word: '个', english: 'Unit', emoji: '' },
            { id: 'nvhaizi', word: '女孩子', english: 'Girl', emoji: '' },
            { id: 'nvsheng', word: '女生', english: 'Female Student', emoji: '' },
            { id: 'nanhaizi', word: '男孩子', english: 'Boy', emoji: '' },
            { id: 'nansheng', word: '男生', english: 'Male Student', emoji: '' },
            { id: 'dajie', word: '大姐', english: 'Eldest Sister', emoji: '' },
            { id: 'erjie', word: '二姐', english: '2nd Sister', emoji: '' },
            { id: 'nver', word: '女儿', english: 'Daughter', emoji: '' },
            { id: 'daxuesheng', word: '大学生', english: 'College Student', emoji: '' },
            { id: 'gaozhongsheng', word: '高中生', english: 'High Schooler', emoji: '' },
            { id: 'chuzhongsheng', word: '初中生', english: 'Middle Schooler', emoji: '' },
            { id: 'shei', word: '谁', english: 'Who', emoji: '' },
            { id: 'jia', word: '家', english: 'Home/Family', emoji: '' },
            { id: 'ji', word: '几', english: 'How many', emoji: '' },
            { id: 'kou', word: '口', english: 'Mouth', emoji: '' },
            { id: 'liang', word: '两', english: 'Two', emoji: '' },
            { id: 'wenti', word: '问题', english: 'Question', emoji: '' },
            { id: 'zuo', word: '做', english: 'Do/Make', emoji: '' },
            { id: 'gongzuo', word: '工作', english: 'Job', emoji: '' },
            { id: 'lvshi', word: '律师', english: 'Lawyer', emoji: '' },
            { id: 'yisheng', word: '医生', english: 'Doctor', emoji: '' },
            { id: 'nianji', word: '年级', english: 'Grade', emoji: '' },
            { id: 'paidui', word: '派对', english: 'Party', emoji: '' },
            { id: 'zai', word: '在', english: 'At', emoji: '' },
            { id: 'nali', word: '哪里', english: 'Where', emoji: '' },
            { id: 'zheli', word: '这里', english: 'Here', emoji: '' },
            { id: 'nali2', word: '那里', english: 'There', emoji: '' },
            { id: 'weishenme', word: '为什么', english: 'Why', emoji: '' },
            { id: 'yinwei', word: '因为', english: 'Because', emoji: '' },
            { id: 'zaofan', word: '早饭', english: 'Breakfast', emoji: '' },
            { id: 'wufan', word: '午饭', english: 'Lunch', emoji: '' },
            { id: 'wanfan', word: '晚饭', english: 'Dinner', emoji: '' },
            { id: 'renshi', word: '认识', english: 'Know', emoji: '' },
            { id: 'hen', word: '很', english: 'Very', emoji: '' },
            { id: 'gaoxing', word: '高兴', english: 'Happy', emoji: '' },
            { id: 'hai', word: '还', english: 'Still', emoji: '' },
            { id: 'xuexiao', word: '学校', english: 'School', emoji: '' },
            { id: 'gongke', word: '功课', english: 'Homework', emoji: '' },
            { id: 'henduo', word: '很多', english: 'Many', emoji: '' },
            { id: 'zhi', word: '只', english: 'Only', emoji: '' },
        ],
    },
    {
        id: 'unit3',
        title: 'Lesson 3',
        color: 'bg-yellow-500',
        icon: '📅',
        words: [
            { id: 'yue', word: '月', english: 'Month', emoji: '' },
            { id: 'hao', word: '号', english: 'Day/Number', emoji: '' },
            { id: 'xingqi', word: '星期', english: 'Week', emoji: '' },
            { id: 'jintian', word: '今天', english: 'Today', emoji: '' },
            { id: 'mingtian', word: '明天', english: 'Tomorrow', emoji: '' },
            { id: 'zuotian', word: '昨天', english: 'Yesterday', emoji: '' },
            { id: 'xianzai', word: '现在', english: 'Now', emoji: '' },
            { id: 'ke', word: '刻', english: 'Quarter', emoji: '' },
            { id: 'dian', word: '点', english: "O'clock", emoji: '' },
            { id: 'zaoshang', word: '早上', english: 'Morning', emoji: '' },
            { id: 'wanshang', word: '晚上', english: 'Evening', emoji: '' },
            { id: 'fen', word: '分', english: 'Minute', emoji: '' },
            { id: 'tian', word: '天', english: 'Day', emoji: '' },
            { id: 'shengri', word: '生日', english: 'Birthday', emoji: '' },
            { id: 'sheng', word: '生', english: 'Born', emoji: '' },
            { id: 'ri', word: '日', english: 'Day/Sun', emoji: '' },
            { id: 'nian', word: '年', english: 'Year', emoji: '' },
            { id: 'jinnian', word: '今年', english: 'This Year', emoji: '' },
            { id: 'sui', word: '岁', english: 'Age', emoji: '' },
            { id: 'yao', word: '要', english: 'Want/Need', emoji: '' },
            { id: 'gen', word: '跟', english: 'With', emoji: '' },
            { id: 'hui', word: '会', english: 'Can', emoji: '' },
            { id: 'kan', word: '看', english: 'Look/Watch', emoji: '' },
            { id: 'qunian', word: '去年', english: 'Last Year', emoji: '' },
            { id: 'qu', word: '去', english: 'Go', emoji: '' },
            { id: 'lai', word: '来', english: 'Come', emoji: '' },
            { id: 'keshi', word: '可是', english: 'But', emoji: '' },
            { id: 'suoyi', word: '所以', english: 'So', emoji: '' },
            { id: 'huijia', word: '回家', english: 'Go Home', emoji: '' },
            { id: 'keyi', word: '可以', english: 'Can/May', emoji: '' },
            { id: 'ban', word: '半', english: 'Half', emoji: '' },
            { id: 'zenmeyang', word: '怎么样', english: 'How about', emoji: '' },
            { id: 'taile', word: '太...了', english: 'Too...', emoji: '' },
            { id: 'ai', word: '爱', english: 'Love', emoji: '' },
            { id: 'jian', word: '见', english: 'See', emoji: '' },
            { id: 'zaijian', word: '再见', english: 'Goodbye', emoji: '' },
            { id: 'chi', word: '吃', english: 'Eat', emoji: '' },
            { id: 'fan', word: '饭', english: 'Rice/Meal', emoji: '' },
            { id: 'haochi', word: '好吃', english: 'Delicious', emoji: '' },
            { id: 'cai', word: '菜', english: 'Dish/Veg', emoji: '' },
            { id: 'xiexie', word: '谢谢', english: 'Thanks', emoji: '' },
            { id: 'canjia', word: '参加', english: 'Attend', emoji: '' },
            { id: 'gei', word: '给', english: 'Give', emoji: '' },
            { id: 'shi', word: '事（儿）', english: 'Matter', emoji: '' },
            { id: 'mang', word: '忙', english: 'Busy', emoji: '' },
        ],
    },
    {
        id: 'unit4',
        title: 'Lesson 4',
        color: 'bg-green-500',
        icon: '🎮',
        words: [
            { id: 'zhoumo', word: '周末', english: 'Weekend', emoji: '' },
            { id: 'zuotian2', word: '昨天', english: 'Yesterday', emoji: '' },
            { id: 'changchang', word: '常常', english: 'Often', emoji: '' },
            { id: 'waiguo', word: '外国', english: 'Foreign', emoji: '' },
            { id: 'qingke', word: '请客', english: 'Treat', emoji: '' },
            { id: 'aihao', word: '爱好', english: 'Hobby', emoji: '' },
            { id: 'dongxi', word: '东西', english: 'Things', emoji: '' },
            { id: 'shangwang', word: '上网', english: 'Surf Web', emoji: '' },
            { id: 'dadianziyouxi', word: '打电子游戏', english: 'Video Games', emoji: '' },
            { id: 'haibian', word: '海边', english: 'Beach', emoji: '' },
            { id: 'da', word: '打', english: 'Play/Hit', emoji: '' },
            { id: 'qiu', word: '球', english: 'Ball', emoji: '' },
            { id: 'dianying', word: '电影', english: 'Movie', emoji: '' },
            { id: 'changge', word: '唱歌（儿）', english: 'Sing', emoji: '' },
            { id: 'chang', word: '唱', english: 'Sing', emoji: '' },
            { id: 'ge', word: '歌（儿）', english: 'Song', emoji: '' },
            { id: 'ting', word: '听', english: 'Listen', emoji: '' },
            { id: 'yinyue', word: '音乐', english: 'Music', emoji: '' },
            { id: 'youde', word: '有的', english: 'Some', emoji: '' },
            { id: 'youdeshihou', word: '有的时候', english: 'Sometimes', emoji: '' },
            { id: 'deshihou', word: '...的时候', english: 'When...', emoji: '' },
            { id: 'yinweisuoyi', word: '因为...所以...', english: 'Because..So', emoji: '' },
            { id: 'fangxue', word: '放学', english: 'Finish School', emoji: '' },
            { id: 'haojiu', word: '好久', english: 'Long time', emoji: '' },
            { id: 'jiu', word: '久', english: 'Long', emoji: '' },
            { id: 'bucuo', word: '不错', english: 'Not bad', emoji: '' },
            { id: 'cuo', word: '错', english: 'Wrong', emoji: '' },
            { id: 'juede', word: '觉得', english: 'Think', emoji: '' },
            { id: 'youyisi', word: '有意思', english: 'Interesting', emoji: '' },
            { id: 'yisi', word: '意思', english: 'Meaning', emoji: '' },
            { id: 'shuijiao', word: '睡觉', english: 'Sleep', emoji: '' },
            { id: 'shui', word: '睡', english: 'Sleep', emoji: '' },
            { id: 'jiao', word: '觉', english: 'Sleep', emoji: '' },
            { id: 'yiqi', word: '一起', english: 'Together', emoji: '' },
            { id: 'zhao', word: '找', english: 'Find', emoji: '' },
            { id: 'bieren', word: '别人', english: 'Others', emoji: '' },
            { id: 'bie', word: '别(的)', english: 'Other', emoji: '' },
            { id: 'cai', word: '才', english: 'Only then', emoji: '' },
            { id: 'le', word: '了', english: 'Particle', emoji: '' },
            { id: 'bang', word: '帮', english: 'Help', emoji: '' },
            { id: 'zhunbei', word: '准备', english: 'Prepare', emoji: '' },
            { id: 'lianxi', word: '练习', english: 'Practice', emoji: '' },
            { id: 'de', word: '得', english: 'Particle', emoji: '' },
            { id: 'jianmian', word: '见面', english: 'Meet', emoji: '' },
            { id: 'huilai', word: '回来', english: 'Come back', emoji: '' },
        ],
    },
    {
        id: 'unit5',
        title: 'Lesson 5',
        color: 'bg-blue-500',
        icon: '☕',
        words: [
            { id: 'kuai', word: '快', english: 'Fast', emoji: '' },
            { id: 'jin', word: '进', english: 'Enter', emoji: '' },
            { id: 'jinlai', word: '进来', english: 'Come in', emoji: '' },
            { id: 'jieshao', word: '介绍', english: 'Introduce', emoji: '' },
            { id: 'yixia', word: '一下', english: 'A bit', emoji: '' },
            { id: 'buhaoyisi', word: '不好意思', english: 'Sorry', emoji: '' },
            { id: 'he', word: '喝', english: 'Drink', emoji: '' },
            { id: 'bei', word: '杯', english: 'Cup', emoji: '' },
            { id: 'ping', word: '瓶', english: 'Bottle', emoji: '' },
            { id: 'shui', word: '水', english: 'Water', emoji: '' },
            { id: 'cha', word: '茶', english: 'Tea', emoji: '' },
            { id: 'dianer', word: '点（儿）', english: 'A little', emoji: '' },
            { id: 'kafei', word: '咖啡', english: 'Coffee', emoji: '' },
            { id: 'kele', word: '可乐', english: 'Coke', emoji: '' },
            { id: 'naicha', word: '奶茶', english: 'Milk Tea', emoji: '' },
            { id: 'zhenzhunaicha', word: '珍珠奶茶', english: 'Boba', emoji: '' },
            { id: 'guozhi', word: '果汁', english: 'Juice', emoji: '' },
            { id: 'dai', word: '带', english: 'Bring', emoji: '' },
            { id: 'lingshi', word: '零食', english: 'Snacks', emoji: '' },
            { id: 'shuiguo', word: '水果', english: 'Fruit', emoji: '' },
            { id: 'binggan', word: '饼干', english: 'Cookie', emoji: '' },
            { id: 'dianxin', word: '点心', english: 'Dim Sum', emoji: '' },
            { id: 'piaoliang', word: '漂亮', english: 'Pretty', emoji: '' },
            { id: 'shuai', word: '帅', english: 'Handsome', emoji: '' },
            { id: 'zuo', word: '坐', english: 'Sit', emoji: '' },
            { id: 'duibuqi', word: '对不起', english: 'Sorry', emoji: '' },
            { id: 'ya', word: '呀', english: '!', emoji: '' },
            { id: 'ba', word: '吧', english: '...', emoji: '' },
            { id: 'tushuguan', word: '图书馆', english: 'Library', emoji: '' },
            { id: 'bangongshi', word: '办公室', english: 'Office', emoji: '' },
            { id: 'deng', word: '等', english: 'Wait', emoji: '' },
            { id: 'liaotian', word: '聊天（儿）', english: 'Chat', emoji: '' },
            { id: 'liao', word: '聊', english: 'Chat', emoji: '' },
            { id: 'tian', word: '天', english: 'Sky/Day', emoji: '' },
            { id: 'buyao', word: '不要', english: "Don't", emoji: '' },
            { id: 'keqi', word: '客气', english: 'Polite', emoji: '' },
            { id: 'yinggai', word: '应该', english: 'Should', emoji: '' },
            { id: 'zenme', word: '怎么', english: 'How', emoji: '' },
        ],
    },
    {
        id: 'unit6',
        title: 'Lesson 6',
        color: 'bg-purple-600',
        icon: '🌺',
        words: [
            { id: 'zui', word: '最', english: 'Most', emoji: '' },
            { id: 'tanxiangshan', word: '檀香山', english: 'Honolulu', emoji: '' },
            { id: 'shengbing', word: '生病', english: 'Sick', emoji: '' },
            { id: 'yihou', word: '以后', english: 'After', emoji: '' },
            { id: 'xiaweiyiyu', word: '夏威夷语', english: 'Hawaiian', emoji: '' },
            { id: 'zhongguocheng', word: '中国城', english: 'Chinatown', emoji: '' },
            { id: 'yiqian', word: '以前', english: 'Before', emoji: '' },
            { id: 'fanguaner', word: '饭馆儿', english: 'Restaurant', emoji: '' },
            { id: 'meige', word: '每个', english: 'Every', emoji: '' },
            { id: 'zuocai', word: '做菜', english: 'Cook', emoji: '' },
            { id: 'dushu', word: '读书', english: 'Study', emoji: '' },
            { id: 'mengxiang', word: '梦想', english: 'Dream', emoji: '' },
            { id: 'chushi', word: '厨师', english: 'Chef', emoji: '' },
            { id: 'zhuan', word: '赚', english: 'Earn', emoji: '' },
            { id: 'xinku', word: '辛苦', english: 'Hard Work', emoji: '' },
            { id: 'xiwang', word: '希望', english: 'Hope', emoji: '' },
            { id: 'tinghua', word: '听话', english: 'Obey', emoji: '' },
            { id: 'buxiao', word: '不孝', english: 'Unfilial', emoji: '' },
            { id: 'youming', word: '有名', english: 'Famous', emoji: '' },
            { id: 'chuantong', word: '传统', english: 'Traditional', emoji: '' },
            { id: 'zhenrenxiu', word: '真人秀', english: 'Reality Show', emoji: '' },
            { id: 'shuohua', word: '说话', english: 'Talk', emoji: '' },
            { id: 'bisai', word: '比赛', english: 'Match', emoji: '' },
            { id: 'nanguo', word: '难过', english: 'Sad', emoji: '' },
            { id: 'ayi', word: '阿姨', english: 'Aunt', emoji: '' },
            { id: 'daren', word: '大人', english: 'Adult', emoji: '' },
            { id: 'kaihui', word: '开会', english: 'Meeting', emoji: '' },
            { id: 'baoming', word: '报名', english: 'Sign up', emoji: '' },
            { id: 'meitian', word: '每天', english: 'Daily', emoji: '' },
            { id: 'shangwu', word: '上午', english: 'Morning', emoji: '' },
            { id: 'xianshou', word: '选手', english: 'Player', emoji: '' },
            { id: 'laizi', word: '来自', english: 'From', emoji: '' },
            { id: 'zhongwu', word: '中午', english: 'Noon', emoji: '' },
            { id: 'guojia', word: '国家', english: 'Country', emoji: '' },
            { id: 'xiawu', word: '下午', english: 'Afternoon', emoji: '' },
            { id: 'xibanya', word: '西班牙', english: 'Spain', emoji: '' },
            { id: 'yueshijian', word: '约时间', english: 'Appoint', emoji: '' },
            { id: 'faguo', word: '法国', english: 'France', emoji: '' },
            { id: 'jie', word: '节', english: 'Period', emoji: '' },
            { id: 'yuenan', word: '越南', english: 'Vietnam', emoji: '' },
            { id: 'shouji', word: '手机', english: 'Phone', emoji: '' },
            { id: 'kaoshi', word: '考试', english: 'Test', emoji: '' },
            { id: 'hanguo', word: '韩国', english: 'Korea', emoji: '' },
            { id: 'xiaokao', word: '小考', english: 'Quiz', emoji: '' },
            { id: 'riben', word: '日本', english: 'Japan', emoji: '' },
            { id: 'ku', word: '酷', english: 'Cool', emoji: '' },
            { id: 'konger', word: '空（儿）', english: 'Free time', emoji: '' },
            { id: 'chonglang', word: '冲浪', english: 'Surf', emoji: '' },
            { id: 'fangbian', word: '方便', english: 'Convenient', emoji: '' },
            { id: 'hula', word: '呼啦', english: 'Hula', emoji: '' },
            { id: 'dao', word: '到', english: 'Arrive', emoji: '' },
            { id: 'xueguo', word: '学过', english: 'Learned', emoji: '' },
            { id: 'huoshan', word: '火山', english: 'Volcano', emoji: '' },
            { id: 'pa', word: '怕', english: 'Fear', emoji: '' },
            { id: 'wahudao', word: '瓦胡岛', english: 'Oahu', emoji: '' },
            { id: 'huo', word: '活', english: 'Live', emoji: '' },
            { id: 'dadao', word: '大岛', english: 'Big Island', emoji: '' },
            { id: 'bukeqi', word: '不客气', english: 'Welcome', emoji: '' },
            { id: 'sichuan', word: '四川', english: 'Sichuan', emoji: '' },
            { id: 'lihai', word: '厉害', english: 'Awesome', emoji: '' },
            { id: 'xiage', word: '下个', english: 'Next', emoji: '' },
            { id: 'chiguo', word: '吃过', english: 'Eaten', emoji: '' },
            { id: 'caipan', word: '裁判', english: 'Referee', emoji: '' },
            { id: 'huanying', word: '欢迎', english: 'Welcome', emoji: '' },
            { id: 'diyi', word: '第一', english: '1st', emoji: '' },
            { id: 'kaishi', word: '开始', english: 'Start', emoji: '' },
            { id: 'jinzhang', word: '紧张', english: 'Nervous', emoji: '' },
            { id: 'zixin', word: '自信', english: 'Confident', emoji: '' },
            { id: 'jiangyou', word: '酱油', english: 'Soy Sauce', emoji: '' },
            { id: 'yong', word: '用', english: 'Use', emoji: '' },
            { id: 'kaoyu', word: '烤鱼', english: 'Grilled Fish', emoji: '' },
            { id: 'kongxincai', word: '空心菜', english: 'Water Spinach', emoji: '' },
            { id: 'ziji', word: '自己', english: 'Self', emoji: '' },
            { id: 'zhiyao', word: '只要', english: 'Only if', emoji: '' },
            { id: 'butong', word: '不同', english: 'Different', emoji: '' },
            { id: 'kaoya', word: '烤鸭', english: 'Roast Duck', emoji: '' },
            { id: 'bi', word: '比', english: 'Compare', emoji: '' },
            { id: 'chaomian', word: '炒面', english: 'Fried Noodle', emoji: '' },
            { id: 'taiwan', word: '台湾', english: 'Taiwan', emoji: '' },
            { id: 'niuruomian', word: '牛肉面', english: 'Beef Noodle', emoji: '' },
            { id: 'ying', word: '赢', english: 'Win', emoji: '' },
            { id: 'xiaoshi', word: '小时', english: 'Hour', emoji: '' },
            { id: 'yiding', word: '一定', english: 'Must', emoji: '' },
            { id: 'shu', word: '输', english: 'Lose', emoji: '' },
            { id: 'meiyouyong', word: '没有用', english: 'Useless', emoji: '' },
            { id: 'banfa', word: '办法', english: 'Way', emoji: '' },
            { id: 'jianada', word: '加拿大', english: 'Canada', emoji: '' },
            { id: 'renhenhao', word: '人很好', english: 'Nice', emoji: '' },
            { id: 'jieshu', word: '结束', english: 'End', emoji: '' },
            { id: 'juesai', word: '决赛', english: 'Finals', emoji: '' },
        ],
    },
];

export const HITBOX_SIZE_PCT = 18;
export const HAND_CURSOR_SIZE_PX = 60;
export const COLLISION_THRESHOLD = 0.15;

export const getRandomGameUnit = (): GameUnit => {
    const allWords = UNITS.flatMap(u => u.words);
    const mixedWords = allWords.sort(() => 0.5 - Math.random()).slice(0, 10);
    return {
        id: 'mixed',
        title: 'Magic Mix',
        color: 'bg-indigo-600',
        icon: '✨',
        words: mixedWords
    };
};